name = "composer"
version = "2.10.1"
type = "tool"

homepage = "https://getcomposer.org"
license = "MIT"

# Shim name (composer) -> runs `php composer.phar`.
bin = [
  "composer.bat",
]
phar = "composer.phar"

[architecture.x64]
url = "https://getcomposer.org/download/2.10.1/composer.phar"
hash = "sha256:345b9c6a98da5c30dcbd4b0d99fc8710bf0ae98a3898eea18f7b2ad9dec93f06"
