name = "mysql"
version = "8.0.46"
type = "database"

homepage = "https://www.mysql.com"
license = "GPL-2.0"

bin = [
  "bin/mysql.exe",
  "bin/mysqldump.exe",
  "bin/mysqladmin.exe",
]

[service]
name = "cove-mysql"
port = 3306

[architecture.x64]
url = "https://cdn.mysql.com/Downloads/MySQL-8.0/mysql-8.0.46-winx64.zip"
hash = ""
