name = "postgresql"
version = "16.10"
type = "database"

homepage = "https://www.postgresql.org"
license = "PostgreSQL"

bin = [
  "bin/psql.exe",
  "bin/pg_dump.exe",
  "bin/pg_restore.exe",
]

[service]
name = "cove-postgresql"
port = 5432

[architecture.x64]
url = "https://get.enterprisedb.com/postgresql/postgresql-16.10-1-windows-x64-binaries.zip"
hash = "sha256:ebb3b6af4fa69dea9951b66855bc4d42dc04e56ccb9aa7024ce3c58bd89d6b0c"
