name = "postgresql"
version = "18.4"
type = "database"

homepage = "https://www.postgresql.org"
license = "PostgreSQL"

bin = [
  "bin/psql.exe",
  "bin/pg_dump.exe",
  "bin/pg_restore.exe",
]

[service]
name = "cove-postgresql"
port = 5432

[architecture.x64]
url = "https://get.enterprisedb.com/postgresql/postgresql-18.4-1-windows-x64-binaries.zip"
hash = "sha256:7effe34c0bf89027b3f171447d351cbc460f4566c8d0f643daec67f140787858"
