name = "mariadb"
version = "12.3.2"
type = "database"

homepage = "https://mariadb.org"
license = "GPL-2.0"

bin = [
  "bin/mariadb.exe",
  "bin/mysql.exe",
  "bin/mysqldump.exe",
]

[service]
name = "cove-mariadb"
port = 3306

[architecture.x64]
url = "https://archive.mariadb.org/mariadb-12.3.2/winx64-packages/mariadb-12.3.2-winx64.zip"
hash = ""
