name = "mailpit"
version = "1.30.1"
type = "service"

homepage = "https://mailpit.axllent.org"
license = "MIT"

bin = [
  "mailpit.exe",
]

[service]
name = "cove-mailpit"
port = 1025

[architecture.x64]
url = "https://github.com/axllent/mailpit/releases/download/v1.30.1/mailpit-windows-amd64.zip"
hash = ""
