name = "php"
version = "8.5.7"
type = "runtime"

homepage = "https://www.php.net"
license = "PHP-3.01"

bin = [
  "php.exe",
  "php-cgi.exe",
]

env_add_path = [
  ".",
]

[architecture.x64]
url = "https://windows.php.net/downloads/releases/php-8.5.7-nts-Win32-vs17-x64.zip"
hash = "sha256:2ff43fea9a243085493b48c7c47152c0678cff0b05c61a3b4f4b43ba22de212c"
